module.exports = {
  important: "",
  future: {},
  purge: false,
  theme: {
    screens: {
      landscape: { raw: "(min-width: 600px) and (max-height: 600px)" },
      computer: { raw: "(min-width: 600px) and (min-height: 600px)" },
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      primary: {
        DEFAULT: "hsl(231, 50%, 50%)",
        light: "hsl(231, 50%, 65%)",
        dark: "hsl(231, 50%, 35%)",
        disabled: "hsl(231, 25%, 50%)",
      },
      secondary: {
        DEFAULT: "hsl(4, 90%, 60%)",
        light: "hsl(4, 90%, 70%)",
        dark: "hsl(4, 90%, 40%)",
        disabled: "hsl(4, 33%, 60%)",
      },
      error: "hsl(349, 85%, 40%)",
    },
    textColor: (theme) => ({
      ...theme("colors"),
      "on-primary": "hsl(0, 0%, 100%)",
      "on-secondary": "hsl(0, 0%, 100%)",
      "on-background": "hsla(0, 0%, 0%, 0.87)",
      "icon-on-background": "hsla(0, 0%, 0%, 0.54)",
      "on-surface": "hsla(0, 0%, 0%, 0.87)",
      "on-error": "hsl(0, 0%, 100%)",
      "on-tooltip": "hsl(0, 0%, 100%)",
    }),
    backgroundColor: (theme) => ({
      ...theme("colors"),
      background: "hsl(0, 0%, 100%)",
      surface: "hsl(0, 0%, 100%)",
      tooltip: "black",
    }),
    spacing: {
      0: 0,
      xs: ".125rem", //2px
      sm: ".25rem", //4px
      med: ".5rem", //8px
      lg: "1rem", //16px
      "2": "2rem", //32px
      "3": "3rem",
      "4": "4rem",
      "6": "6rem",
      "8": "8rem",
      "16": "16rem",
    },
    width: {
      auto: "auto",
      full: "100%",
      screen: "100vw",
      1: "1rem",
      2: "2rem",
      3: "3rem",
      4: "4rem",
      6: "6rem",
      8: "8rem",
      10: "10rem",
      12: "12rem",
      14: "14rem",
      16: "16rem",
      20: "20rem",
      24: "24rem",
      "1/4": "25%",
      "1/2": "50%",
      "3/4": "75",
      "1/3": "33.333333%",
      "2/3": "66.666666%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
    },
    height: {
      auto: "auto",
      full: "100%",
      screen: "100vh",
      1: "1rem",
      2: "2rem",
      3: "3rem",
      4: "4rem",
      6: "6rem",
      8: "8rem",
      10: "10rem",
      12: "12rem",
      14: "14rem",
      16: "16rem",
      20: "20rem",
      24: "24rem",
    },
  },
  corePlugins: [
    "alignContent",
    "alignItems",
    "alignSelf",
    "backgroundColor",
    "borderColor",
    "borderRadius",
    "borderWidth",
    "boxShadow",
    "container",
    "cursor",
    "display",
    "flex",
    "flexDirection",
    "flexGrow",
    "flexShrink",
    "fontSize",
    "fontWeight",
    "height",
    "justifyContent",
    "justifyItems",
    "justifySelf",
    "lineHeight",
    "margin",
    "maxHeight",
    "minWidth",
    "maxWidth",
    "opacity",
    "overflow",
    "padding",
    "position",
    "textAlign",
    "textColor",
    "textOverflow",
    "verticalAlign",
    "visibility",
    "width",
    "zIndex",
  ],
  variantOrder: [
    "children",
    "children-first",
    "DEFAULT",
    "first",
    "last",
    "odd",
    "even",
    "visited",
    "checked",
    "group-hover",
    "group-focus",
    "focus-within",
    "hover",
    "focus",
    "focus-visible",
    "active",
    "disabled",
  ],
  variants: {
    extend: {
      margin: ["children", "children-first", "DEFAULT", "first"],
      padding: ["children", "DEFAULT"],
      flex: ["children", "DEFAULT"],
      flexGrow: ["children", "DEFAULT"],
      width: ["children", "DEFAULT"],
      cursor: ["children", "DEFAULT"],
      display: ["children", "DEFAULT"],
    },
  },
  plugins: [require("tailwindcss-children")],
};
