module.exports = {
  important: "#root",
  future: {},
  purge: [],
  theme: {
    screens: {
      landscape: { raw: "(min-width: 600px) and (max-height: 600px)" },
      computer: { raw: "(min-width: 600px) and (min-height: 600px)" },
    },
    colors: {
      "on-primary": "hsl(0, 0%, 100%)",
      primary: {
        lt: "hsl(231, 50%, 65%)",
        DEFAULT: "hsl(231, 50%, 50%)",
        dk: "hsl(231, 50%, 35%)",
      },
      "on-secondary": "hsl(0, 0%, 100%)",
      secondary: {
        lt: "hsl(4, 90%, 65%)",
        DEFAULT: "hsl(4, 90%, 50%)",
        dk: "hsl(4, 90%, 35%)",
      },
      "on-background": "hsla(0, 0%, 0%, 0.87)",
      background: {
        DEFAULT: "hsl(0, 0%, 100%)",
        icon: "hsla(0, 0%, 0%, 0.54)",
      },
      "on-surface": "hsla(0, 0%, 0%, 0.87)",
      surface: {
        DEFAULT: "hsl(0, 0%, 100%)",
      },
      "on-error": "hsl(0, 0%, 100%)",
      error: {
        DEFAULT: "hsl(349, 85%, 40%)",
      },
    },
    extend: {
      spacing: {
        sm: "0.5rem",
        med: "1rem",
        lg: "2rem",
      },
    },
  },
  corePlugins: [
    "alignContent",
    "alignItems",
    "alignSelf",
    "backgroundColor",
    "backgroundOpacity",
    "borderColor",
    "borderOpacity",
    "borderRadius",
    "borderStyle",
    "borderWidth",
    "boxShadow",
    "cursor",
    "display",
    "flex",
    "flexDirection",
    "flexGrow",
    "flexShrink",
    "flexWrap",
    "fontSize",
    "fontWeight",
    "height",
    "justifyContent",
    "justifyItems",
    "justifySelf",
    "lineHeight",
    "margin",
    "maxHeight",
    "maxWidth",
    "opacity",
    "overflow",
    "padding",
    "position",
    "textAlign",
    "textColor",
    "textOpacity",
    "textOverflow",
    "verticalAlign",
    "visibility",
    "width",
    "zIndex",
  ],
  variants: {
    margin: ({ before }) => before(["children", "children-first", "DEFAULT"]),
    flex: ({ before }) => before(["children", "DEFAULT"]),
    width: ({ before }) => before(["children", "DEFAULT"]),
    cursor: ({ before }) => before(["children", "DEFAULT"]),
  },
  plugins: [require("tailwindcss-children")],
};
